services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: portal
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./docker/db:/docker-entrypoint-initdb.d"
    networks:
      - portal-docker
  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
    networks:
      - portal-docker
  php-apache:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
      dockerfile: ./docker/php-apache/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
      - "9001:9001"
    volumes:
      - .:/var/www/html
    environment:
      - APP_KEY=SomeRandomStringToAddSecurity123
      - APP_ENV=development
      - APP_DEBUG=true
#      - APACHE_RUN_USER=apache-www-volume
#      - APACHE_RUN_GROUP=apache-www-volume
      - PHP_IDE_CONFIG=serverName=nette_freelancer-portal
#      - XDEBUG_CONFIG=remote_host=172.20.0.1 remote_port=9001
      - XDEBUG_MODE = DEBUG
      - PORTAL_ADMIN_USERNAME=admin@portal.cz
      - PORTAL_ADMIN_PASSWORD=admin123456
      - PORTAL_USER_USERNAME=user@portal.cz
      - PORTAL_USER_PASSWORD=user123456
    networks:
      - portal-docker
networks:
  portal-docker:
    driver: bridge